# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-Eksblowfish
version:      0.000
version_from: lib/Crypt/Eksblowfish.pm
installdirs:  site
requires:
    MIME::Base64:                  2.21
    XSLoader:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
