---
name: Crypt-Eksblowfish
version: 0.003
author:
  - Solar Designer (solar at openwall.com)
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
abstract: the Eksblowfish block cipher
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Exporter: 0
  MIME::Base64: 2.21
  XSLoader: 0
  base: 0
  fields: 0
  perl: 5.006
  strict: 0
  warnings: 0
build_requires:
  ExtUtils::CBuilder: 0.15
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
dynamic_config: 0
provides:
  Crypt::Eksblowfish:
    file: lib/Crypt/Eksblowfish.pm
    version: 0.003
  Crypt::Eksblowfish::Bcrypt:
    file: lib/Crypt/Eksblowfish/Bcrypt.pm
    version: 0.003
  Crypt::Eksblowfish::Blowfish:
    file: lib/Crypt/Eksblowfish/Blowfish.pm
    version: 0.003
  Crypt::Eksblowfish::Family:
    file: lib/Crypt/Eksblowfish/Family.pm
    version: 0.003
  Crypt::Eksblowfish::Subkeyed:
    file: lib/Crypt/Eksblowfish/Subkeyed.pm
    version: 0.003
  Crypt::Eksblowfish::Uklblowfish:
    file: lib/Crypt/Eksblowfish/Uklblowfish.pm
    version: 0.003
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: module
