---
abstract: 'the Eksblowfish block cipher'
author:
  - 'Solar Designer (solar at openwall.com)'
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  ExtUtils::CBuilder: 0.15
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.006
  strict: 0
  warnings: 0
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-Eksblowfish
provides:
  Crypt::Eksblowfish:
    file: lib/Crypt/Eksblowfish.pm
    version: 0.009
  Crypt::Eksblowfish::Bcrypt:
    file: lib/Crypt/Eksblowfish/Bcrypt.pm
    version: 0.009
  Crypt::Eksblowfish::Blowfish:
    file: lib/Crypt/Eksblowfish/Blowfish.pm
    version: 0.009
  Crypt::Eksblowfish::Family:
    file: lib/Crypt/Eksblowfish/Family.pm
    version: 0.009
  Crypt::Eksblowfish::Subkeyed:
    file: lib/Crypt/Eksblowfish/Subkeyed.pm
    version: 0.009
  Crypt::Eksblowfish::Uklblowfish:
    file: lib/Crypt/Eksblowfish/Uklblowfish.pm
    version: 0.009
requires:
  Carp: 0
  Class::Mix: 0.001
  Exporter: 0
  MIME::Base64: 2.21
  XSLoader: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.009
